package io.github.gldiazcardenas.commons.bean.validation;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Validation error generated by applying business rules to an object.
 *
 * @author Gabriel Diaz, 17/12/2020.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ValidationIssue {

    /**
     * Type of validation error.
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    public enum Type {
        ERROR, WARNING, INFO
    }

    private String message;
    private Type type;

    public ValidationIssue() {
        super();
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Type getType() {
        return type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return type + ": " + message;
    }

    public static ValidationIssue error(String message) {
        ValidationIssue result = new ValidationIssue();
        result.type = Type.ERROR;
        result.message = message;
        return result;
    }

    public static ValidationIssue warning(String message) {
        ValidationIssue result = new ValidationIssue();
        result.type = Type.WARNING;
        result.message = message;
        return result;
    }

    public static ValidationIssue info(String message) {
        ValidationIssue result = new ValidationIssue();
        result.type = Type.INFO;
        result.message = message;
        return result;
    }

}
